name = "aveyo-website"
compatibility_date = "2024-01-01"

# Cloudflare Pages configuration
[site]
bucket = "./dist"

# Build configuration
[build]
command = "npm run build"

[build.upload]
format = "service-worker"
